services:
  my-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ../postgresql-mount:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
